/**
 * Map of supported code block languages for CodeMirror editor.
 * Source: https://codemirror.net/5/mode/
 *
 * By Dulapah Vibulsanti (https://dulapahv.dev)
 */

export const codeBlockLanguages: Record<string, string> = {
  "": "Plain Text",
  apl: "APL",
  asn1: "ASN.1",
  asterisk: "Asterisk",
  brainfuck: "Brainfuck",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  ceylon: "Ceylon",
  clojure: "Clojure",
  gss: "Closure Stylesheets",
  cmake: "CMake",
  cobol: "COBOL",
  coffeescript: "CoffeeScript",
  commonlisp: "Common Lisp",
  crystal: "Crystal",
  css: "CSS",
  cypher: "Cypher",
  cython: "Cython",
  d: "D",
  dart: "Dart",
  django: "Django",
  dockerfile: "Dockerfile",
  diff: "Diff",
  dtd: "DTD",
  dylan: "Dylan",
  ebnf: "EBNF",
  ecl: "ECL",
  eiffel: "Eiffel",
  elixir: "Elixir",
  elm: "Elm",
  erlang: "Erlang",
  factor: "Factor",
  fcl: "FCL",
  forth: "Forth",
  fortran: "Fortran",
  fsharp: "F#",
  gas: "Gas",
  gherkin: "Gherkin",
  go: "Go",
  groovy: "Groovy",
  haml: "HAML",
  handlebars: "Handlebars",
  haskell: "Haskell",
  haxe: "Haxe",
  html: "HTML",
  http: "HTTP",
  idl: "IDL",
  java: "Java",
  js: "JavaScript",
  jsx: "JSX",
  jinja2: "Jinja2",
  julia: "Julia",
  kotlin: "Kotlin",
  less: "LESS",
  livescript: "LiveScript",
  lua: "Lua",
  md: "Markdown",
  mathematica: "Mathematica",
  mbox: "mbox",
  mirc: "mIRC",
  modelica: "Modelica",
  mscgen: "MscGen",
  mumps: "MUMPS",
  nginx: "Nginx",
  nsis: "NSIS",
  ntriples: "N-Triples",
  objc: "Objective C",
  ocaml: "OCaml",
  octave: "Octave",
  oz: "Oz",
  pascal: "Pascal",
  pegjs: "PEG.js",
  perl: "Perl",
  pgp: "PGP",
  php: "PHP",
  pig: "Pig Latin",
  powershell: "PowerShell",
  properties: "Properties",
  protobuf: "ProtoBuf",
  pug: "Pug",
  puppet: "Puppet",
  python: "Python",
  q: "Q",
  r: "R",
  rpm: "RPM",
  rst: "reStructuredText",
  ruby: "Ruby",
  rust: "Rust",
  sas: "SAS",
  sass: "Sass",
  spreadsheet: "Spreadsheet",
  scala: "Scala",
  scheme: "Scheme",
  scss: "SCSS",
  shell: "Shell",
  sieve: "Sieve",
  slim: "Slim",
  smalltalk: "Smalltalk",
  smarty: "Smarty",
  solr: "Solr",
  soy: "Soy",
  stylus: "Stylus",
  sql: "SQL",
  sparql: "SPARQL",
  squirrel: "Squirrel",
  swift: "Swift",
  stex: "sTeX",
  tcl: "Tcl",
  textile: "Textile",
  tiddlywiki: "Tiddlywiki",
  tiki: "Tiki",
  toml: "TOML",
  tornado: "Tornado",
  troff: "Troff",
  tsx: "TSX",
  ttcn: "TTCN",
  turtle: "Turtle",
  twig: "Twig",
  vb: "VB.NET",
  vbscript: "VBScript",
  velocity: "Velocity",
  verilog: "Verilog",
  vhdl: "VHDL",
  vue: "Vue.js",
  webidl: "Web IDL",
  wast: "WebAssembly",
  xml: "XML",
  xquery: "XQuery",
  yacas: "Yacas",
  yaml: "YAML",
  z80: "Z80",
};
